apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: 616755845023.dkr.ecr.ap-northeast-2.amazonaws.com/bar:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: test-mysql.cefbp1srbkww.ap-northeast-2.rds.amazonaws.com
        - name: WORDPRESS_DB_PASSWORD
          value: testrdspass
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_NAME
          value: testDB
        ports:
        - containerPort: 80
          name: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
